import { blobToDataUrl, dataUrlToBlob } from "./blob.utils";
import { readLogoAt, writeLogoAt } from "./logo.utils";
import { SavedQr, listSavedQrs, readSavedQr, writeSavedQr } from "./saved-qr.utils";
import { normalizeTemplateType } from "./template.utils";

/**
 * Export / import as a single JSON file.
 *
 * Without accounts, clearing browsing data wipes everything, so this is the only
 * way out. Logos are base64 here — the one place that's the right call, since the
 * file is leaving the browser and IndexedDB's quota stops being the constraint.
 */
export const BACKUP_VERSION = 1;

const APP_TAG = "gaweqr";

/** Guardrails for a file that may not have come from us. */
const MAX_RECORDS = 500;
const MAX_THUMBNAIL_CHARS = 200_000;
const MAX_PARAMS_CHARS = 8_000;
const MAX_ID_CHARS = 128;

export interface BackupFile {
  app: typeof APP_TAG;
  version: number;
  exportedAt: string;
  codes: SavedQr[];
  /** logoKey → data URL. */
  logos: Record<string, string>;
}

export interface ImportResult {
  added: number;
  updated: number;
  skipped: number;
}

export async function buildBackup(): Promise<BackupFile> {
  const codes = await listSavedQrs();
  const logos: Record<string, string> = {};

  for (const record of codes) {
    if (!record.logoKey) continue;

    const blob = await readLogoAt(record.logoKey);

    if (blob) logos[record.logoKey] = await blobToDataUrl(blob);
  }

  return {
    app: APP_TAG,
    version: BACKUP_VERSION,
    exportedAt: new Date().toISOString(),
    codes,
    logos,
  };
}

export function backupFilename(): string {
  return `gaweqr-backup-${new Date().toISOString().slice(0, 10)}.json`;
}

/**
 * Everything below treats the file as untrusted. It was chosen from a disk and
 * may have been hand-edited or generated by something else entirely; a bad field
 * should cost that one record, not the whole import.
 */
function toRecord(value: unknown): SavedQr | null {
  if (!value || typeof value !== "object") return null;

  const raw = value as Record<string, unknown>;

  if (typeof raw.id !== "string" || !raw.id || raw.id.length > MAX_ID_CHARS) return null;
  if (typeof raw.params !== "string" || raw.params.length > MAX_PARAMS_CHARS) return null;

  const name = typeof raw.name === "string" && raw.name.trim() ? raw.name.trim() : "Untitled QR";
  // Rendered into an <img src>, so nothing but a base64 image is accepted.
  const thumbnail =
    typeof raw.thumbnail === "string" &&
    raw.thumbnail.startsWith("data:image/") &&
    raw.thumbnail.length <= MAX_THUMBNAIL_CHARS
      ? raw.thumbnail
      : undefined;
  const createdAt = typeof raw.createdAt === "number" ? raw.createdAt : Date.now();
  const updatedAt = typeof raw.updatedAt === "number" ? raw.updatedAt : createdAt;

  return {
    id: raw.id,
    name: name.slice(0, 120),
    // Falls back to free text for any template this build doesn't know.
    template: normalizeTemplateType(typeof raw.template === "string" ? raw.template : undefined),
    params: raw.params,
    logoKey: typeof raw.logoKey === "string" ? raw.logoKey : undefined,
    thumbnail,
    createdAt,
    updatedAt,
  };
}

/** Throws with a message meant for the user. */
export function parseBackup(text: string): BackupFile {
  let parsed: unknown;

  try {
    parsed = JSON.parse(text);
  } catch {
    throw new Error("That file isn't valid JSON.");
  }

  if (!parsed || typeof parsed !== "object") throw new Error("That file isn't a GaweQR backup.");

  const raw = parsed as Record<string, unknown>;

  if (raw.app !== APP_TAG) throw new Error("That file isn't a GaweQR backup.");
  if (typeof raw.version !== "number" || raw.version > BACKUP_VERSION) {
    throw new Error("That backup was made by a newer version of GaweQR.");
  }
  if (!Array.isArray(raw.codes)) throw new Error("That backup has no QR codes in it.");
  if (raw.codes.length > MAX_RECORDS) {
    throw new Error(`That backup holds more than ${MAX_RECORDS} codes.`);
  }

  const codes = raw.codes.map(toRecord).filter((record): record is SavedQr => !!record);

  if (!codes.length) throw new Error("That backup has no readable QR codes in it.");

  const logos: Record<string, string> = {};
  const rawLogos = raw.logos;

  if (rawLogos && typeof rawLogos === "object") {
    Object.entries(rawLogos as Record<string, unknown>).forEach(([key, value]) => {
      if (typeof value === "string" && value.startsWith("data:image/")) logos[key] = value;
    });
  }

  return {
    app: APP_TAG,
    version: raw.version,
    exportedAt: typeof raw.exportedAt === "string" ? raw.exportedAt : "",
    codes,
    logos,
  };
}

/**
 * Merges rather than replaces, and a colliding id keeps whichever copy is newer.
 * That makes importing the same file twice a no-op instead of a duplicate.
 */
export async function applyBackup(backup: BackupFile): Promise<ImportResult> {
  const result: ImportResult = { added: 0, updated: 0, skipped: 0 };

  for (const incoming of backup.codes) {
    const existing = await readSavedQr(incoming.id);

    if (existing && existing.updatedAt >= incoming.updatedAt) {
      result.skipped += 1;
      continue;
    }

    const logoDataUrl = incoming.logoKey ? backup.logos[incoming.logoKey] : undefined;
    const logo = logoDataUrl ? dataUrlToBlob(logoDataUrl) : null;

    if (incoming.logoKey && logo) await writeLogoAt(incoming.logoKey, logo);

    const record: SavedQr = {
      ...incoming,
      // Don't point at a logo the file didn't carry.
      logoKey: logo ? incoming.logoKey : undefined,
    };

    if (await writeSavedQr(record)) {
      if (existing) result.updated += 1;
      else result.added += 1;
    } else {
      result.skipped += 1;
    }
  }

  return result;
}
